// gegblge.h - empty stub implementation.
// Generated by script/gen_occt_stubs.py; bodies are intentionally
// unimplemented and are to be filled in with OCCT-based logic.

#include <gegblge.h>
#include <gelibver.h>

// NvGe
const NvGeLibVersion NvGe::gLibVersion;
