// gegbl.h - empty stub implementation.
// Generated by script/gen_occt_stubs.py; bodies are intentionally
// unimplemented and are to be filled in with OCCT-based logic.

#include <gegbl.h>
#include <NvAChar.h>
#include <getol.h>
#include <gevec3d.h>

// NvGeContext
NvGeTol NvGeContext::gTol;

void (*NvGeContext::gErrorFunc)();

void (*NvGeContext::gOrthoVector)(const NvGeVector3d&,NvGeVector3d&);

void* (*NvGeContext::gAllocMem)(size_t);

void (*NvGeContext::gFreeMem)(void*);

// Debug-only declarations (mirrors #ifndef NDEBUG in the header).
#ifndef NDEBUG
void (*NvGeContext::gAssertFunc)(const NCHAR *condition, const NCHAR *filename, int lineNumber, const NCHAR *status);

#endif
